name: umay_db
description: A lightweight embedded NoSQL database for Dart and Flutter. Inspired by Laravel Eloquent ORM and Bitcask storage architecture.
version: 1.0.0
homepage: https://github.com/pishguy/umay
repository: https://github.com/pishguy/umay.git
issue_tracker: https://github.com/pishguy/umay/issues

environment:
  sdk: ^3.11.0

dev_dependencies:
  lints: ^5.0.0
